version: '3.7'
services:
  pg:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: wacdo
    volumes:
      - ./pg-tables-and-data.sql:/docker-entrypoint-initdb.d/init.sql
